---
fail_fast: false
minimum_pre_commit_version: "2.6.0"
repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: 212db41760d7fc45d736d5eb94a483d0d2a12049  # frozen: v0.16.0 To update run: `pre-commit autoupdate --freeze`
    hooks:
      - id: terraform-docs-go
        args:
          - "--config=.config/.terraform-docs.yaml"
          - "--lockfile=false"
          - "--recursive"
          - "--recursive-path=examples/"
          - "./"
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0
    hooks:
      - id: terraform_fmt
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      - id: detect-private-key
